# Generated by Django 3.2 on 2023-02-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_unique_relationship'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_relationship',
        ),
    ]
