# Generated by Django 3.2 on 2023-01-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230129_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(to='reviews.Genre'),
        ),
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
