# Generated by Django 3.2 on 2023-02-04 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_review_unique_title_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1, message='Рейтинг не может быть меньше 1!'), django.core.validators.MaxValueValidator(10, message='Рейтинг не может быть больше 10!')]),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
